# Generated by Django 6.0 on 2026-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
